image: node:20

pipelines:
  branches:
    develop:
      - step:
          name: Build and Deploy to Development
          caches:
            - node
          script:
            - npm install # Instala dependencias
            - npm run build -- --configuration=development # Genera la build de Angular
            - npm install -g netlify-cli # Instala el CLI de Netlify
            - netlify deploy --prod --dir=./dist/portfolio-app/ --site=dcb7beab-8690-4dd4-b7a8-23a1ff947a68
    staging:
      - step:
          name: Build and Deploy to Staging
          caches:
            - node
          script:
            - npm install
            - npm run build -- --configuration=staging
            - npm install -g netlify-cli
            - netlify deploy --prod --dir=./dist/portfolio-app/ --site=dcb7beab-8690-4dd4-b7a8-23a1ff947a68
    production:
      - step:
          name: Build and Deploy to Production
          caches:
            - node
          script:
            - npm install
            - npm run build -- --configuration=production
            - npm install -g netlify-cli
            - netlify deploy --prod --dir=./dist/portfolio-app/ --site=dcb7beab-8690-4dd4-b7a8-23a1ff947a68
