image: node:20 # Utilizamos una imagen de Node.js para la pipeline

pipelines:
  branches:
    develop:
      - step:
          name: Build and Deploy to Development
          caches:
            - node
          script:
            - npm install # Instala dependencias
            - npm run build -- --configuration=development # Genera la build de Angular
            - scp -r ./dist/mi-app/ usuario@desarrollo.host.com:/ruta/del/servidor # Sube los archivos al servidor de desarrollo
    staging:
      - step:
          name: Build and Deploy to Staging
          caches:
            - node
          script:
            - npm install
            - npm run build -- --configuration=staging
            - scp -r ./dist/mi-app/ usuario@staging.host.com:/ruta/del/servidor # Sube los archivos al servidor de pruebas
    production:
      - step:
          name: Build and Deploy to Production
          caches:
            - node
          script:
            - npm install
            - npm run build -- --configuration=production
            - scp -r ./dist/mi-app/ usuario@produccion.host.com:/ruta/del/servidor # Sube los archivos al servidor de producción
